<a href="https://colab.research.google.com/github/rizwinmk/python_assessment/blob/main/numpy_act.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create a NumPy array with values from 10 to 49 (inclusive).
● Reshape it into a 4x10 matrix.
● Then extract the last column from the reshaped matrix

In [4]:
import numpy as np
arr=np.arange(10,50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [5]:
arr.shape

(40,)

In [6]:
arr=arr.reshape(4,10)
arr


array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [7]:
last_col=arr[:,-1]
last_col

array([19, 29, 39, 49])

Create two 3×3 matrices:
One filled with all 5s , One with values from 1 to 9
● Add the two matrices
● Multiply them element-wise
● Then find the transpose of the result

In [8]:
A=np.full((3,3),5)
A

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [9]:
B=np.arange(1,10).reshape(3,3)
B

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
add=A+B
add

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [11]:
mul=A*B
mul

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [12]:
mul.T

array([[ 5, 20, 35],
       [10, 25, 40],
       [15, 30, 45]])

3. Create a NumPy array of 15 random integers between 10 and 100. ● Replace all values greater than 50 with -1 ● Count how many values were replaced.

In [13]:
arr=np.random.randint(10,100,size=15)
arr

array([13, 72, 79, 88, 19, 29, 48, 75, 72, 14, 16, 96, 23, 42, 15])

In [14]:
count=np.sum(arr>50)

In [15]:

print(count)

6


In [16]:
arr=np.where(arr>50,-1,arr)
arr

array([13, -1, -1, -1, 19, 29, 48, -1, -1, 14, 16, -1, 23, 42, 15])

4. Generate a 5×4 array with random values between 0 and 1 (float).
● Find the row with the maximum sum of values.
● Normalize each row using the formula:


In [17]:
arr=np.random.random((5,4))
arr

array([[0.12526778, 0.96913567, 0.2422616 , 0.12248237],
       [0.69717967, 0.34599934, 0.06886497, 0.21813668],
       [0.97495261, 0.21241913, 0.35850851, 0.67966904],
       [0.56482924, 0.07084962, 0.85361323, 0.48741919],
       [0.36552344, 0.87615502, 0.48116684, 0.32767286]])

In [18]:
row_sum=np.sum(arr,axis=1)
row_sum

array([1.45914742, 1.33018067, 2.22554929, 1.97671128, 2.05051817])

In [19]:

max_row_index = np.argmax(row_sum)
print(max_row_index)

2


In [20]:
print(arr[max_row_index])

[0.97495261 0.21241913 0.35850851 0.67966904]


In [21]:
row_min = arr.min(axis=1, keepdims=True)
row_max = arr.max(axis=1, keepdims=True)

normalized = (arr - row_min) / (row_max - row_min)
print(normalized)

[[0.0032899  1.         0.14147376 0.        ]
 [1.         0.44107574 0.         0.23757476]
 [1.         0.         0.19158421 0.61275986]
 [0.63107127 0.         1.         0.532178  ]
 [0.06900968 1.         0.27985227 0.        ]]


5

In [22]:
arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])

In [23]:
arr

array([1, 3, 5, 3, 7, 9, 1, 5, 5])

In [24]:
print(np.unique(arr))

[1 3 5 7 9]


In [25]:
values, counts = np.unique(arr, return_counts=True)
print(values)
print(counts)

[1 3 5 7 9]
[2 2 3 1 1]


In [26]:
dup=values[counts>1]
dup

array([1, 3, 5])

6


In [27]:
arr = np.arange(1,37).reshape(6,6)
submatrix = arr[1:5, 1:5]
even_numbers = submatrix[submatrix % 2 == 0]
print(submatrix)
print(even_numbers)

[[ 8  9 10 11]
 [14 15 16 17]
 [20 21 22 23]
 [26 27 28 29]]
[ 8 10 14 16 20 22 26 28]


7


In [28]:
arr = np.arange(12).reshape(3, 4)
print(arr)

reshaped = arr.reshape(2, 6)
print(reshaped)

flattened = reshaped.flatten()
print(flattened)

back_to_4x3 = flattened.reshape(4, 3)
print(back_to_4x3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


8


In [29]:
a = np.array([[1, 2], [3, 4]])
print(a)

# Append a new row [5, 6]
a = np.append(a, [[5, 6]], axis=0)
print(a)

# Append a new column [7, 8, 9]
a = np.append(a, [[7], [8], [9]], axis=1)
print(a)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]
 [5 6 9]]


9


In [30]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

joined = np.concatenate([a, b, c])
print(joined)

matrix = joined.reshape(3, 3)
print(matrix)

diagonal = np.diagonal(matrix)
print(diagonal)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]


10

In [31]:
arr = np.arange(1, 21)
print(arr)

result = arr[(arr % 3 == 0) | (arr % 5 == 0)]
print(result)

count = len(result)
print(count)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 3  5  6  9 10 12 15 18 20]
9
